USE ROLE ACCOUNTADMIN;

//IN YOUR LOCAL ACCOUNT, CREATE OR REPLACE A DATABASE WITH A SUBSET OF DATA
CREATE OR REPLACE DATABASE SOURCEDB;
CREATE OR REPLACE SCHEMA SALES;

//CREATE A SEQUENCE TO USE FOR THE TABLE. 
CREATE OR REPLACE SEQUENCE SEQ_SALES
START = 1
INCREMENT = 1;

//CREATE A THE SALES_MASTER TABLE
CREATE OR REPLACE TABLE SALES.SALES_MASTER
(ID NUMBER,
STORE_NO INT,
SALES_DATE TIMESTAMP_TZ,
SALES INT,
REGION VARCHAR(10));

INSERT INTO SALES.SALES_MASTER
SELECT SOURCEDB.SALES.SEQ_SALES.NEXTVAL, 100, '2021-06-07 02:21:10.00 -0700', 100, 'APAC'
UNION
SELECT SEQ_SALES.NEXTVAL, 100, '2021-06-08 02:21:10.00 -0700', 190, 'APAC'
UNION
SELECT SEQ_SALES.NEXTVAL, 100, '2021-06-09 02:21:10.00 -0700', 104, 'APAC'
UNION
SELECT SEQ_SALES.NEXTVAL, 100, '2021-06-10 02:21:10.00 -0700', 150, 'APAC'
UNION
SELECT SEQ_SALES.NEXTVAL, 101, '2021-06-07 02:21:10.00 -0700', 3201, 'APAC'
UNION
SELECT SEQ_SALES.NEXTVAL, 101, '2021-06-08 02:21:10.00 -0700', 2987, 'APAC'
UNION
SELECT SEQ_SALES.NEXTVAL, 101, '2021-06-09 02:21:10.00 -0700', 3241, 'APAC'
UNION
SELECT SEQ_SALES.NEXTVAL, 101, '2021-06-10 02:21:10.00 -0700', 3829, 'APAC'
UNION
SELECT SEQ_SALES.NEXTVAL, 102, '2021-06-07 02:21:10.00 -0700', 675, 'EUR'
UNION
SELECT SEQ_SALES.NEXTVAL, 102, '2021-06-08 02:21:10.00 -0700', 435, 'EUR'
UNION
SELECT SEQ_SALES.NEXTVAL, 102, '2021-06-09 02:21:10.00 -0700', 867, 'EUR'
UNION
SELECT SEQ_SALES.NEXTVAL, 102, '2021-06-10 02:21:10.00 -0700', 453, 'EUR';


SELECT * FROM SALES.SALES_MASTER;

//CREATE A DATABASE TO STORE THE APAC SALES TABLE AND SECURE VIEWS
CREATE OR REPLACE DATABASE PRIMARYDB;
CREATE OR REPLACE SCHEMA SALES;

CREATE OR REPLACE TABLE PRIMARYDB.SALES.SALES_MASTER_APAC
(ID NUMBER,
STORE_NO INT,
SALES_DATE TIMESTAMP_TZ,
SALES INT);

//SEED THE TABLE WITH EXISTING RECORDS
INSERT INTO PRIMARYDB.SALES.SALES_MASTER_APAC
SELECT ID, STORE_NO,SALES_DATE, SALES FROM SOURCEDB.SALES.SALES_MASTER WHERE REGION = 'APAC'; 

//CREATE A SECURE VIEW FOR EACH FRANCHISEE STORE
CREATE OR REPLACE SECURE VIEW PRIMARYDB.SALES.FRANCHISEE_100 AS SELECT * FROM PRIMARYDB.SALES.SALES_MASTER_APAC WHERE STORE_NO = 100;

CREATE OR REPLACE SECURE VIEW PRIMARYDB.SALES.FRANCHISEE_101 AS SELECT * FROM PRIMARYDB.SALES.SALES_MASTER_APAC WHERE STORE_NO = 101;

SELECT * FROM PRIMARYDB.SALES.FRANCHISEE_100;

SELECT * FROM PRIMARYDB.SALES.FRANCHISEE_101;

//SET UP A STREAM TO RECORD CHANGES MADE TO THE SOURCE TABLE
CREATE OR REPLACE STREAM SOURCEDB.SALES.MYSTREAM ON TABLE SOURCEDB.SALES.SALES_MASTER APPEND_ONLY = TRUE;

//SET UP A TASK TO LIFT THE CHANGES FROM THE SOURCE DATABASE AND INSERT THEM TO THE PRIMARYDB DATABASE
CREATE OR REPLACE TASK SOURCEDB.SALES.MYTASK1
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = '1 MINUTE'
WHEN
  SYSTEM$STREAM_HAS_DATA('MYSTREAM')
AS
  INSERT INTO PRIMARYDB.SALES.SALES_MASTER_APAC SELECT SOURCEDB.SALES.SEQ_SALES.NEXTVAL,STORE_NO, SALES_DATE, SALES FROM MYSTREAM WHERE METADATA$ACTION = 'INSERT' AND STORE_NO IN (100,101) AND REGION = 'APAC';

ALTER TASK SOURCEDB.SALES.MYTASK1 RESUME;

//INSERT A NEW SALES RECORD INTO THE SALES MASTER TABLE FOR STORE 100
INSERT INTO SOURCEDB.SALES.SALES_MASTER
SELECT SOURCEDB.SALES.SEQ_SALES.NEXTVAL, 100, '2021-06-13 02:21:10.00 -0700', 999, 'APAC';

//CHECK THE STREAM FOR THE RECORD ADDED
SELECT * FROM SOURCEDB.SALES.MYSTREAM WHERE METADATA$ACTION = 'INSERT';

//CHECK FOR THE NEW RECORD
SELECT * 
FROM PRIMARYDB.SALES.SALES_MASTER_APAC;

//PROMOTE THE NEW DATABASE AS PRIMARY
ALTER DATABASE PRIMARYDB ENABLE REPLICATION TO ACCOUNTS AZURE_EASTUS2.ACMEPROVIDERACCOUNT2;

//REPLICATE YOUR EXISTING DATABASE TO ANOTHER REGION IN APAC
CREATE OR REPLACE DATABASE SECONDARYDB
  AS REPLICA OF AP-SOUTHEAST-2.ACMEPROVIDERACCOUNT1.PRIMARYDB;

//SCHEDULE REFRESH OF THE SECONDARY DATABASE
CREATE OR REPLACE TASK REFRESH_SECONDARYDB_TASK
  WAREHOUSE = MYWH
  SCHEDULE = '10 MINUTE'
AS
  ALTER DATABASE SECONDARYDB REFRESH;

ALTER TASK REFRESH_SECONDARYDB_TASK RESUME;

//CREATE OR REPLACE A SHARE FOR EACH FRANCHISEE
CREATE OR REPLACE SHARE SHARE100;
CREATE OR REPLACE SHARE SHARE101;

//ADD OBJECTS TO THE SHARE:
GRANT USAGE ON DATABASE SECONDARYDB TO SHARE SHARE100;
GRANT USAGE ON SCHEMA SECONDARYDB.SALES TO SHARE SHARE100;

GRANT SELECT ON VIEW SECONDARYDB.SALES.FRANCHISEE_100 TO SHARE SHARE100;

GRANT USAGE ON DATABASE SECONDARYDB TO SHARE SHARE101;
GRANT USAGE ON SCHEMA SECONDARYDB.SALES TO SHARE SHARE101;

GRANT SELECT ON VIEW SECONDARYDB.SALES.FRANCHISEE_101 TO SHARE SHARE101;

//ADD ONE OR MORE CONSUMER ACCOUNTS TO THE SHARE
ALTER SHARE SHARE100 ADD ACCOUNTS=FRANCHISEE_ACCOUNT_100;

ALTER SHARE SHARE101 ADD ACCOUNTS=FRANCHISEE_ACCOUNT_101;